class HDClassObj_82 {
	var name_0: String?
	var name_1: String?
	var name_2: String?
	var name_3: String?
	var name_4: String?
	var name_5: String?
	var name_6: String?
	var name_7: String?
	var name_8: String?
	var name_9: String?
	var name_10: String?
	var name_11: String?
	var name_12: String?
	var name_13: String?
	var name_14: String?
	var name_15: String?
	var name_16: String?
	var name_17: String?
	var name_18: String?
	var name_19: String?
	var name_20: String?
	var name_21: String?
	var name_22: String?
	var name_23: String?
	var name_24: String?
	var name_25: String?
	var name_26: String?
	var name_27: String?
	var name_28: String?
	var name_29: String?
	var name_30: String?
	var name_31: String?
	var name_32: String?
	var name_33: String?
	var name_34: String?
	var name_35: String?
	var name_36: String?
	var name_37: String?
	var name_38: String?
	var name_39: String?
	var name_40: String?
	var name_41: String?
	var name_42: String?
	var name_43: String?
	var name_44: String?
	var name_45: String?
	var name_46: String?
	var name_47: String?
	var name_48: String?
	var name_49: String?
	var name_50: String?
	var name_51: String?
	var name_52: String?
	var name_53: String?
	var name_54: String?
	var name_55: String?
	var name_56: String?
	var name_57: String?
	var name_58: String?
	var name_59: String?
	var name_60: String?
	var name_61: String?
	var name_62: String?
	var name_63: String?
	var name_64: String?
	var name_65: String?
	var name_66: String?
	var name_67: String?
	var name_68: String?
	var name_69: String?
	var name_70: String?
	var name_71: String?
	var name_72: String?
	var name_73: String?
	var name_74: String?
	var name_75: String?
	var name_76: String?
	var name_77: String?
	var name_78: String?
	var name_79: String?
	var name_80: String?
	var name_81: String?
}
