class HDClassObj_25 {
	var name_0: String?
	var name_1: String?
	var name_2: String?
	var name_3: String?
	var name_4: String?
	var name_5: String?
	var name_6: String?
	var name_7: String?
	var name_8: String?
	var name_9: String?
	var name_10: String?
	var name_11: String?
	var name_12: String?
	var name_13: String?
	var name_14: String?
	var name_15: String?
	var name_16: String?
	var name_17: String?
	var name_18: String?
	var name_19: String?
	var name_20: String?
	var name_21: String?
	var name_22: String?
	var name_23: String?
	var name_24: String?
}
